[versions]
activityCompose = "1.11.0"
agp = "8.13.1"
composeBom = "2025.11.00"
coreKtx = "1.17.0"
crashlytics = "3.0.6"
cucumber = "7.18.1" # do not update to last release as some libraries will not work at last release.
espressoCore = "3.7.0"
firebase = "34.6.0"
googleid = "1.1.1"
googleservices = "4.4.4"
hilt = "2.57.2"
hiltNavigationCompose = "1.3.0"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlin = "2.2.21"
ksp = "2.2.20-2.0.3"
lifecycleRuntimeKtx = "2.9.4"
oliviermarteaux = "3.6.1"
credentials = "1.5.0"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
cucumber-android = { module = "io.cucumber:cucumber-android", version.ref = "cucumber" }
cucumber-java = { module = "io.cucumber:cucumber-java", version.ref = "cucumber" }
cucumber-junit = { module = "io.cucumber:cucumber-junit", version.ref = "cucumber" }
cucumber-messages = { module = "io.cucumber:messages", version.ref = "cucumber" }
cucumber-picocontainer = { module = "io.cucumber:cucumber-picocontainer", version.ref = "cucumber" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase" }
firebase-crashlytics-ndk = { module = "com.google.firebase:firebase-crashlytics-ndk" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
firebase-storage = { module = "com.google.firebase:firebase-storage" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
oliviermarteaux-compose = { module = "com.github.OlivierMarteaux.shared-android-library:compose", version.ref = "oliviermarteaux" }
oliviermarteaux-core = { module = "com.github.OlivierMarteaux.shared-android-library:core", version.ref = "oliviermarteaux" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose" }
play-services-credentials = {module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials"}
androidx-credentials = {module = "androidx.credentials:credentials", version.ref = "credentials"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
googleservices = { id = "com.google.gms.google-services", version.ref = "googleservices" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }